<div class="row">

    <h1>Earthquake service</h1>
    <br>
    <h3>Here there's a list of all earthquakes around the world from the <a href="http://earthquake.usgs.gov">USGS</a></h3>
    <br>
    <br>
    <?php foreach ($this->earthquakes as $earthquake) { ?>

        <div class="row">
            <p class="title"><?php $earthquake->title() ?></p>
            <p class="description"><?php $earthquake->description() ?></p>
            <p class="mag"><?php $earthquake->mag() ?></p>
            <p class="time"><?php $earthquake->time() ?></p>
        </div>
    <?php } ?>
</div>
